# Generated by Django 5.2 on 2026-08-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110, verbose_name='(انگلیسی) نام')),
                ('verbose_name', models.CharField(blank=True, max_length=110, null=True, verbose_name='نام (فارسی)')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='شناسه')),
            ],
        ),
    ]
