# Generated by Django 5.2 on 2026-08-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_options_alter_category_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=110, verbose_name='نام (انگلیسی)'),
        ),
    ]
