# Generated by Django 5.2 on 2026-08-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='seo_description',
            field=models.TextField(blank=True, help_text='این توضیحات برای سئو و جستجوی بهتر در خود سایت است', null=True, verbose_name='توضیحات(مربوط به سئو)'),
        ),
    ]
