# Generated by Django 5.2 on 2026-08-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_seo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='slug', unique=True, verbose_name='شناسه'),
            preserve_default=False,
        ),
    ]
