# Generated by Django 5.2 on 2026-06-23 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_alter_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^(\\+98|0)?9\\d{9}$')], verbose_name='شماره تلفن'),
        ),
    ]
