# Generated by Django 5.2 on 2026-06-23 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, null=True, unique=True, validators=[django.core.validators.RegexValidator('^(\\+98|0)?9\\d{9}$')], verbose_name='شماره تلفن'),
        ),
    ]
