# Generated by Django 5.2 on 2026-06-23 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='customuser',
            table_comment=None,
        ),
    ]
