# Generated by Django 5.2 on 2026-06-24 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_table_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'حساب کاربری', 'verbose_name_plural': 'حساب\u200cهای کاربری'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gitea_user_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='شناسه کاربر در Gitea'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید با فرمت +989xxxxxxxxx باشد.', regex='^\\+989\\d{9}$')], verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='وب\u200cسایت'),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='accounts',
        ),
    ]
