# Generated by Django 5.2 on 2026-08-27 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customuser_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='website',
        ),
    ]
