# Generated by Django 5.2 on 2026-07-12 10:51

import blog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='موضوع')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='خلاصه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=blog.models.post_thumbnail_upload_path, verbose_name='تصویر شاخص')),
                ('write_at', models.DateTimeField(auto_now_add=True, verbose_name='نوشته شده در')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش شده در')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
                'db_table': 'post',
            },
        ),
    ]
