# Generated by Django 5.2 on 2026-07-25 12:59

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(upload_to=blog.models.post_thumbnail_upload_path, verbose_name='تصویر شاخص'),
        ),
    ]
