# Generated by Django 5.2 on 2026-08-01 18:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='write_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='نوشته شده در'),
            preserve_default=False,
        ),
    ]
