# Generated by Django 5.2 on 2026-08-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comment_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_pin',
            field=models.BooleanField(default=False, verbose_name='سنجاق شده'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('delete', 'حذف شده'), ('in_review', 'در حال بررسی'), ('okay', 'مورد تایید')], default='in_review', max_length=20, verbose_name='وضعیت'),
        ),
    ]
