# Generated by Django 5.2 on 2026-08-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_comment_is_pin_alter_comment_status'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='core.category', verbose_name='برچسب ها'),
        ),
    ]
