# Generated by Django 5.2 on 2026-08-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_categories'),
        ('core', '0004_category_seo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='core.category', verbose_name='برچسب ها'),
        ),
    ]
