# Generated by Django 5.2 on 2026-08-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comment_word_count_alter_comment_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='word_count',
        ),
        migrations.AddField(
            model_name='post',
            name='word_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد کلمات نوشته شده'),
        ),
    ]
