# Generated by Django 5.2 on 2026-08-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_comment_writer_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_views',
            field=models.PositiveIntegerField(default=0, verbose_name='بازدید ها'),
        ),
    ]
