# Generated by Django 5.2 on 2026-08-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_post_views'),
        ('core', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='core.category', verbose_name='دسته بندی ها'),
        ),
    ]
