# Generated by Django 5.2 on 2026-08-17 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110, verbose_name='موضوع')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('solved', models.BooleanField(default=False, verbose_name='حل شده')),
                ('is_pin', models.BooleanField(default=False, verbose_name='ویژه')),
                ('write_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ مطرح شدن')),
                ('solve_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حل شدن')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
                'db_table': 'questions',
            },
        ),
    ]
