# Generated by Django 5.2 on 2026-08-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('programing', 'برنامه نویسی'), ('technical', 'فنی'), ('general', 'عمومی')], default='programing', max_length=110, verbose_name='مدل سوال'),
            preserve_default=False,
        ),
    ]
