# Generated by Django 5.2 on 2026-08-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_category_slug'),
        ('qa', '0003_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='categories',
            field=models.ManyToManyField(to='core.category', verbose_name='برچسب ها'),
        ),
    ]
