# Generated by Django 5.2 on 2026-08-27 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_question_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='qa.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('programming', 'برنامه نویسی'), ('technical', 'فنی'), ('general', 'عمومی')], max_length=110, verbose_name='مدل سوال'),
        ),
    ]
